# Generated by Django 3.1.1 on 2020-10-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=200, verbose_name='Краткое наименование')),
                ('reg_id', models.CharField(max_length=200, unique=True, verbose_name='Алкокод')),
                ('capacity', models.FloatField(null=True, verbose_name='Объем')),
                ('volume', models.FloatField(verbose_name='Крепость')),
            ],
            options={
                'verbose_name': 'Алкогольная продукция',
                'verbose_name_plural': 'Алкогольная продукция',
            },
        ),
        migrations.CreateModel(
            name='FA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'verbose_name': 'Справка по форме А',
                'verbose_name_plural': 'Справки по форме А',
            },
        ),
        migrations.CreateModel(
            name='FB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'verbose_name': 'Справка по форме Б',
                'verbose_name_plural': 'Справки по форме Б',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=12, verbose_name='ФСРАР ИД')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=12, verbose_name='КПП')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('country', models.PositiveIntegerField()),
                ('region_code', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='RestsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=36, verbose_name='Идентификатор')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('stock', '1 регистр'), ('shop', '2 регистр')], max_length=6, verbose_name='Тип остатков')),
                ('status', models.CharField(choices=[('loaded', 'Загружены'), ('send_ac', 'Передан в УТМ'), ('error', 'Ошибка')], max_length=10, verbose_name='Статус')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.workplace')),
            ],
            options={
                'verbose_name': 'Документ с остатками',
                'verbose_name_plural': 'Документы с остатками',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('identity', models.CharField(max_length=36)),
                ('doc_id', models.CharField(max_length=40)),
                ('doc_type', models.CharField(max_length=40)),
                ('result', models.BooleanField()),
                ('result_date', models.DateTimeField()),
                ('result_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcode', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WayBillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('shipping_date', models.DateTimeField()),
                ('ttn', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('loaded', 'Загружена'), ('send_ac', 'К подтверждению (Передан в УТМ)'), ('wait_ac', 'К подтверждению (Ожидание квитанции о проведении)'), ('confirm', 'Подтверждена'), ('reject', 'Отменена получателем'), ('send_reject', 'К отмене'), ('cancel', 'Отменена отправителем'), ('error', 'Ошибка')], default='loaded', max_length=11)),
                ('comment', models.CharField(max_length=40, null=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.producer')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.workplace')),
            ],
            options={
                'verbose_name': 'Входящая товаро-транспортная накладная',
                'verbose_name_plural': 'Входяще товаро-транспортные накладные',
            },
        ),
        migrations.CreateModel(
            name='WayBillData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('alcohol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.alcohol')),
                ('fa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.fa')),
                ('fb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.fb')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.waybilllist')),
            ],
        ),
        migrations.CreateModel(
            name='RestsStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('alcohol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.alcohol')),
                ('fa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.fa')),
                ('fb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.fb')),
                ('rest_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.restslist')),
            ],
            options={
                'verbose_name': 'Остатки 1 регистр',
                'verbose_name_plural': 'Остатки 1 регистр',
            },
        ),
        migrations.CreateModel(
            name='RestsShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('alcohol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTMWatch.alcohol')),
                ('rest_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.restslist')),
            ],
            options={
                'verbose_name': 'Остатки 2 регистр',
                'verbose_name_plural': 'Остатки 2 регистр',
            },
        ),
        migrations.AddField(
            model_name='alcohol',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.producer'),
        ),
        migrations.AddField(
            model_name='alcohol',
            name='v_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.vcode'),
        ),
    ]
