# Generated by Django 3.1.1 on 2020-10-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0002_auto_20201014_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='workplace',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UTMWatch.workplace'),
            preserve_default=False,
        ),
    ]
