# Generated by Django 3.1.1 on 2020-10-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0004_auto_20201014_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restsshop',
            name='rest_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restlist_restsshop', to='UTMWatch.restslist'),
        ),
        migrations.AlterField(
            model_name='restsstock',
            name='rest_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restlist_reststock', to='UTMWatch.restslist'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='delete_requests',
            field=models.BooleanField(verbose_name='Удалять обработанные документы'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='disabled',
            field=models.BooleanField(verbose_name='Исключить из автоматической обработки'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='load_ttn',
            field=models.BooleanField(verbose_name='Загружать накладные'),
        ),
    ]
