# Generated by Django 3.1.1 on 2020-10-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0007_restheader_shopposition_stockposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='ou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_ou', to='UTMWatch.ou'),
        ),
    ]
