# Generated by Django 3.1.1 on 2020-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0008_auto_20201015_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restheader',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='status',
            field=models.CharField(choices=[('loaded', 'Загружены'), ('send_ac', 'Передан в УТМ'), ('error', 'Ошибка')], default='send_ac', max_length=10, verbose_name='Статус'),
        ),
    ]
