# Generated by Django 3.1.1 on 2020-10-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0009_auto_20201015_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restheader',
            name='request_id',
            field=models.CharField(max_length=36, null=True, verbose_name='Идентификатор'),
        ),
    ]
