# Generated by Django 3.1.1 on 2020-10-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0010_auto_20201015_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('critical', 'Критическая ошибка')], max_length=10)),
                ('msg', models.CharField(max_length=500)),
                ('module', models.CharField(max_length=100)),
            ],
        ),
    ]
