# Generated by Django 3.1.3 on 2020-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0014_auto_20201113_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockposition',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
