# Generated by Django 3.1.3 on 2020-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0015_auto_20201113_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fa',
            options={'verbose_name': 'Справка по форме А', 'verbose_name_plural': 'Справок по форме А'},
        ),
        migrations.AlterModelOptions(
            name='fb',
            options={'verbose_name': 'Справка по форме Б', 'verbose_name_plural': 'Справок по форме Б'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='reply_id',
            field=models.CharField(max_length=36, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='vcode',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
