# Generated by Django 3.1.3 on 2020-11-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0016_auto_20201117_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockposition',
            name='fa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fa', to='UTMWatch.fa'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='fb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb', to='UTMWatch.fb'),
        ),
        migrations.AlterField(
            model_name='vcode',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
