# Generated by Django 3.1.3 on 2020-11-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0017_auto_20201118_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopposition',
            old_name='rest_list',
            new_name='header',
        ),
    ]
