# Generated by Django 3.1.3 on 2020-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0021_restheader_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restheader',
            name='send_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
