# Generated by Django 3.1.3 on 2020-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTMWatch', '0023_auto_20201127_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restheader',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
