# Generated by Django 3.1.1 on 2020-10-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201015_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restsshop',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='restsshop',
            name='rest_list',
        ),
        migrations.RemoveField(
            model_name='restsstock',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='restsstock',
            name='fa',
        ),
        migrations.RemoveField(
            model_name='restsstock',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='restsstock',
            name='rest_list',
        ),
        migrations.DeleteModel(
            name='RestsList',
        ),
        migrations.DeleteModel(
            name='RestsShop',
        ),
        migrations.DeleteModel(
            name='RestsStock',
        ),
    ]
