# Generated by Django 3.1.1 on 2020-10-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
