# Generated by Django 3.1.3 on 2020-11-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.workplace')),
            ],
        ),
    ]
