# Generated by Django 3.1.3 on 2020-11-27 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20201118_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Исходящий запрос', 'verbose_name_plural': 'Исходящие запросы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterModelOptions(
            name='vcode',
            options={'verbose_name': 'Вид продукции', 'verbose_name_plural': 'Виды продукции'},
        ),
        migrations.AlterModelOptions(
            name='waybilldata',
            options={'verbose_name': 'Позиция накладной', 'verbose_name_plural': 'Позиции накладной'},
        ),
        migrations.AlterModelOptions(
            name='waybilllist',
            options={'verbose_name': 'Входящая накладная', 'verbose_name_plural': 'Входящие накладные'},
        ),
        migrations.AddField(
            model_name='restheader',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restheader',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='request_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='kpp',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='КПП'),
        ),
    ]
