# Generated by Django 3.1.3 on 2020-12-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20201127_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.producer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='v_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.vcode', verbose_name='Вид алкогольной продукции'),
        ),
        migrations.AlterField(
            model_name='fa',
            name='reg_id',
            field=models.CharField(max_length=18, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='fb',
            name='reg_id',
            field=models.CharField(max_length=18, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='ou',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Исключить из обработки'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.PositiveIntegerField(verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='region_code',
            field=models.PositiveIntegerField(verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='Метка времени'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.workplace', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата из ЕГАИС'),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='status',
            field=models.CharField(choices=[('loaded', 'Загружены'), ('send_ac', 'Передан в УТМ'), ('send_to', 'К передаче'), ('error', 'Ошибка')], default='send_to', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.workplace', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='shopposition',
            name='alcohol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.alcohol', verbose_name='Алкогольная продукция'),
        ),
        migrations.AlterField(
            model_name='shopposition',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restheader_shopposition', to='API.restheader', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='shopposition',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='alcohol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.alcohol', verbose_name='Алкогольная продукция'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='fa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fa', to='API.fa', verbose_name='Справка А'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='fb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb', to='API.fb', verbose_name='Справка Б'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restheader_stockposition', to='API.restheader', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='stockposition',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='vcode',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vcode',
            name='vcode',
            field=models.IntegerField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='ou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_ou', to='API.ou', verbose_name='Организация'),
        ),
    ]
