# Generated by Django 3.1.3 on 2020-12-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20201202_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restheader',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='restheader',
            name='status',
            field=models.CharField(choices=[('loaded', 'Загружены'), ('send_ac', 'Передан в УТМ'), ('send_to', 'К передаче'), ('error', 'Ошибка')], default='send_ac', max_length=10, verbose_name='Статус'),
        ),
    ]
