# Generated by Django 3.1.3 on 2020-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_auto_20201207_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Метка времени'),
        ),
    ]
