# Generated by Django 3.1.3 on 2020-12-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('API', '0027_auto_20201207_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='periodic_task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workplace_task', to='django_celery_beat.periodictask', verbose_name='Номер переодической задачи'),
        ),
    ]
