# Generated by Django 3.1.3 on 2020-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('API', '0028_workplace_periodic_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='periodic_task',
        ),
        migrations.AddField(
            model_name='workplace',
            name='periodic_task',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='workplace_task', to='django_celery_beat.PeriodicTask', verbose_name='Переодические задачи'),
        ),
    ]
