# Generated by Django 3.1.3 on 2020-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('API', '0029_auto_20201208_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='periodic_task',
            field=models.ManyToManyField(related_name='workplace_task', to='django_celery_beat.PeriodicTask', verbose_name='Переодические задачи'),
        ),
    ]
