# Generated by Django 3.1.3 on 2020-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('API', '0032_workplace_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='task',
            field=models.ManyToManyField(to='django_celery_beat.PeriodicTask'),
        ),
    ]
