# Generated by Django 3.1.3 on 2020-12-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_auto_20201214_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='task',
        ),
    ]
