# Generated by Django 3.1.3 on 2020-12-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_periodictask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodicTask',
        ),
    ]
