# Generated by Django 3.1.3 on 2020-12-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('API', '0036_delete_periodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.workplace')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
